### ISSUE TITLE
USB cable with loose connection -> T2 AU stuck with RED Input LEDs

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#148] opened 2018-06-13 18:00 UTC
My post content from the forum: https://www.consoletuner.com/forum/viewtopic.php?f=27&t=9132#p65706

I have a USB cable with a loose connection (don't know if this is the right word), when I move the cable a bit the controller sometimes disconnects from the T2 with "AU" showing up on the T2 and a red INPUT-A led.
When I disconnect the controller and reconnect it the LED stays red.
Connecting the controller to INPUT-B will turn the INPUT-B LED red, T2 is still showing AU.
Sometimes the T2 drop out to E4 after staying in red led mode for some time (with the controller still connected).

This only seems to happen with newer controllers, ds4 from ps4pro and I can't tell the other version of the controller that does that as it is a evil controller and I can't find any numbers on it and don't want to open this one.

With older ones (jdm-010,jdm-030) I can't get the T2 to stay in AU mode / red led.
There it just connects again when I replug the usb cable or move it a bit again.

I know "replacing the cable" is the best option, but it should be able to reconnect with all version of the ds4 controller without going to a unresponsive state where I can only get it working again by removing the cables from the T2 or going to P mode and leaving it again. I think this should be investigated.

I am on newest firmware 0.98.1.50 (released today).

**Comment by J2Kbr** [comment] 2018-06-25 11:20
As confirmed in the topic this issue seems to be resolved. Closing. Please comment if any relevant information arises.

**Closed as completed by J2Kbr** 2018-06-25 11:20 UTC

**Comment by reebzzremote-beep** [comment] 2026-01-07 19:27
i am having the same issue, how do i fix it?
