### ISSUE TITLE
XBOX ELITE on PS4 keeps random dancing

### ISSUE THREAD

**Issue by yohimbe110** [J2Kbr/TitanTwo#14] opened 2016-10-06 10:16 UTC
Sometimes it works one hour sometimes 15 mins.
T2 is connectet with ps4 in B and xbe in A.
Prog in laptop. short wires.
Ingame in my case cod i keep standing and circling around and around until unplug elite from its micro usb and then it works again

**Comment by omasseau** [comment] 2016-10-29 19:55
Have you tried another USB cable than the one provided with the Titan Tow ?

**Comment by J2Kbr** [comment] 2016-11-06 10:44
Please check if the issue is fixed on firmware 0.77B. If not, please comment below to reopen this bug tracker. Thanks.

**Closed by J2Kbr** 2016-11-06 10:44 UTC
Labels: question
