### ISSUE TITLE
Nintendo Switch Pro Controller no longer working on Xbox One.

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/TitanTwo#87] opened 2017-11-14 15:20 UTC
In reference to my post on the forum [https://www.consoletuner.com/forum/viewtopic.php?f=27&t=7295](url)
I will update this with new info as I am able to test more scenarios.

**Comment by J2Kbr** [comment] 2017-11-24 14:25
I couldn't reproduce this issue. The test I did was:

Connect the Titan Two to Xbox One (first model) with Elite controller on INPUT-B. After the authentication I plugged the Switch Pro controller on INPUT-A, everything worked as expected. I am now just waiting a game update to install to test while playing, but I expect it to work as well.

If your procedure was different than mine or if you have any extra info on this issue, please let me know.

Thanks.

**Comment by CrispyPixels** [comment] 2017-11-25 01:22
I have been unable to get this to repeat as of the latest software update. May have been related to the brown out voltage change? It is working now though.

**Comment by J2Kbr** [comment] 2017-11-25 08:12
You are right, possible this is related with the brown-out voltage, which was fixed in a recent update. So let's close this issue. Thanks.

**Closed as completed by J2Kbr** 2017-11-25 08:12 UTC
