### ISSUE TITLE
Regular crackling noise when using headset

### ISSUE THREAD

**Issue by omasseau** [J2Kbr/TitanTwo#39] opened 2017-02-17 16:51 UTC
There is a very annoying crackling noise when using the headset with my PS4 Pro controller connected to the T2 (which is connected to the PS4 pro).

It makes the headset unusable when playing with the T2.

**Comment by J2Kbr** [comment] 2017-03-12 13:19
omasseau, thank you for reporting this issue. I am currently testing controllers headset on PS4, using the PS4 Pro controller and enabling the PS4 Settings > Devices > Controllers > Communication Method > Use USB Cable.

Tested with mono and stereo headsets.

**Connections:** The headset on the controller jack, PS4 controller on Input-B of the Titan Two and Titan Two output port connected to PS4.

Tested using the "Adjust Microphone Level" to speak and hear sounds. The sound is clear and loud, no issues were detected other than occasional noise that seems to be **originated from the jack connection**, as it happens only when moving the head or messing with the jack/cable. Disabling the microphone on the headset completely stops this noise.

_Side note:_ the Titan Two was powered by an external power supply, but this shouldn't make any difference on the results.

After you update your Titan Two to firmware 0.100B (to be released within the upcoming days), please check if the noises you reported stopped or are caused by what I describe above. If the cause is other, please reopen this issue with instruction of how I can reproduce the issue. Thanks.

**Closed as completed by J2Kbr** 2017-03-12 13:19 UTC
